### ISSUE TITLE
Improve form on mobile 

### ISSUE THREAD

**Issue by leeomara** [ryanjagar/bid-value-reduction-worksheet#3]
The form is hard to use on a phone (eg iPhone Xs). In particular, it’s hard to understand what is what.

The field labels are abbreviated so much that most or indiscernable. See the attached screenshot. 

![test](https://user-images.githubusercontent.com/93003/140616161-691f55d6-4d02-41df-8a4e-cf336eb05946.png)

Maybe the table can linearize or something at narrow screen width, or something?

**Comment by ryanjagar** [comment]
I like the linerize.  Given how dense some of the text is, it might be the best approach.

**Comment by ryanjagar** [comment]
- [ ] Owner
- [ ] Location
- [ ] Labour
- [ ] Total Bid Value Reduction

**Comment by ryanjagar** [comment]
Closed by PR #12
